### ISSUE TITLE
Remove the extra node_modules folder in the root directory

### ISSUE THREAD

**Issue by MohitR1999** [MohitR1999/react-apps#3]

**Comment by hosseinnedaee** [comment]
hi @MohitR1999 
I have a question, Why should we deploy node_modules directory on GitHub. shouldn't it be git ignored?

**Comment by hosseinnedaee** [comment]
we can create .gitignore file an put this as content of that:
`# Dependency directories
node_modules/`
after that the node_module directory doesnt pushed to the github.
each person just need to run `npm install` command to have all necessary node_modules.

Can I work on it?
